version: "3.7"

services:
  mysql:
    image: docker.io/bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=carShop
      - MYSQL_USER=carShop
      - MYSQL_PASSWORD=carShop
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3099:3306
    # command: '--default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql